isomerpages/moe-tampinessec

_our-people/Staff Organisational Structure.md, index.md
=> SEC and banner image

_our-school/Tampinesian Code of Conduct/Image of Tampinesian.md
Hairstyle & general appearance
=> Hairstyle & general appearance

_others/Students/Students' Portal.md
=> sec 3 subj combi exercise microsite 

_data/navigation.yml, _our-people/Staff Organisational Structure.md
=> Nav bar and staff list 

index.md
=> removed resources

index.md
=> remove announcement

_others/Calendar.md, _others/Students/Weekly Assembly Venues.md, _others/Teachers' Portal.md, _others/collection.yml
removed calendar & added assembly venues
=> removed calendar & added assembly venues

_others/Parents/1) Important Helplines.md, _our-people/Executive and Administrative Staff.md
=> CHANGES TO EAS LIST

_others/Teachers' Portal.md
Tidied up the teachers' portal links (standardized formatting, removed duplicates, rearranged sequence)
Added myskillsfuture portal (Pretti's request), removed ecareers (link is broken - hacked?)
Thank you!
=> Teachers portal links

index.md, pages/37th Annual Awards Day and Speech Day.md, pages/38th Annual Awards Day and Speech Day.md
Edited the previous 37th page to 38th, added the writeup. 
Created a new infobar in homepage to link to it.
=> 38th awards day and speech day

_cca/Visual & Performing Arts/Show Choir.md
=> added Ivan's name to Show Choir

index.md
Also cleaned up 2023 items/announcements from homepage
=> Created a link to DSA on homepage

_others/Students/Students' Portal.md
=> Added mid year hol hw links in student portal

_others/Students/Students' Portal.md
Due to security issues, timetable will no longer be posted on website. Sem 1 timetable also taken down so ppl do not think our website is outdated without sem 2 TT
Thank you!
=> Deleted Sem 1 timetable

pages/Privacy Statement.md, pages/terms-of-use.md
=> Replaced outdated Terms of Use and Privacy statement

_cca/Clubs/InfoComm Club.md, _cca/Clubs/Maker Faire.md, _cca/Sports/Basketball.md, _cca/Sports/Football.md, _cca/Sports/Netball.md, _cca/Uniformed Groups/Girl Guides.md, _cca/Uniformed Groups/National Cadet Corps (Land).md, _cca/Visual & Performing Arts/Art Club.md, _cca/Visual & Performing Arts/Concert Band.md, _cca/Visual & Performing Arts/Dance Dynamics.md, _our-curriculum/Craft & Technology.md, _our-curriculum/English Language and Literature Department.md, _our-curriculum/Information & Communications Technology.md, _our-curriculum/Mathematics Department.md, _our-curriculum/Mother Tongue Department.md, _our-curriculum/Physical Education Department.md, _our-curriculum/Science Department.md
updated staff lists in CCAs and depts
=> updated staff lists in CCAs and depts

_our-curriculum/English Language and Literature Department.md
…d","fileName":"English Language and Literature Department.md","userId":"1557"}
=> ELL update

_our-curriculum/English Language and Literature Department.md
…d","fileName":"English Language and Literature Department.md","userId":"1557"}
=> Updated ELL page

_our-curriculum/English Language and Literature Department.md
…d","fileName":"English Language and Literature Department.md","userId":"1557"}
=> update to ELL page's heading

_our-co-curriculum/Direct School Admission (DSA).md
=> Updated some DSA dates
